name: Test
run-name: Test editor end-to-end
on:
  workflow_dispatch:
  push:
    branches: ["main"] # replace "main" with the default branch
  pull_request:
    branches: ["main"]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - name: Linux
          #   os: ubuntu-latest
          - name: macOS
            os: macos-latest
          # - name: Windows
          #   os: windows-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: leanprover/lean-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          lake-package-directory: "demo/server/LeanProject"
          use-mathlib-cache: false
          build: true
          test: false
          lint: false
      - name: install elan (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          set -exo pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf > elan-init.sh
          sh elan-init.sh -y
          elan toolchain install stable
          elan default stable
          source ~/.profile
      - name: run lake build (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd demo/server/LeanProject
          lake build

      - name: install elan (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
          echo 1 | powershell -ExecutionPolicy Bypass -f elan-init.ps1
          del elan-init.ps1
        shell: pwsh
      - name: add elan to PATH (Windows)
        if: matrix.os == 'windows-latest'
        run: (Resolve-Path ~/.elan/bin).Path >> $Env:GITHUB_PATH
        shell: pwsh
      - name: run lake build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          CD demo\server\LeanProject
          lake build
        shell: pwsh

      - uses: actions/setup-node@v3
      - run: npm install --loglevel verbose
      - run: npm audit
        if: matrix.os == 'ubuntu-latest'
        continue-on-error: true
      - run: npm run test
