name: Test
run-name: Test editor end-to-end
on:
  workflow_dispatch:
  push:
    branches: ["main"] # replace "main" with the default branch
  pull_request:
    branches: ["main"]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # uses lean standard action with all default input values
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "demo/server/LeanProject"
          use-mathlib-cache: false
          build: true
          test: false
          lint: false
      - uses: actions/setup-node@v3
      - run: npm install --loglevel verbose
      - run: npm audit
        continue-on-error: true
      - run: npm run test
