name: Test
run-name: Test editor end-to-end
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: print lean and lake versions
        run: |
          lean --version
          lake --version
      - run: npm install
      - run: npm run test
